version: '2'

services:
    php:
        build: ./docker/php5.6-fpm
        ports:
            - 9010:9000
        volumes:
            - .:/var/www/poc-redis
        working_dir: /var/www/poc-redis

    nginx:
        build: ./docker/nginx
        ports:
            - 8282:80
        links:
            - php
        volumes_from:
            - php
#        volumes:
#            - ./docker/logs/nginx/:/var/log/nginx

    mysql:
        image: mysql:latest
        volumes:
          - /var/lib/mysql
        ports:
          - "3306:3306"
        links:
            - php
        environment:
            MYSQL_ROOT_PASSWORD: poc-redis
            MYSQL_DATABASE: poc-redis
            MYSQL_USER: poc-redis
            MYSQL_PASSWORD: poc-redis

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
          SERVICE_80_NAME: 'phpmyadmin'
          SERVICE_80_TAGS: 'http'
          MYSQL_HOST: 'root'
          MYSQL_PORT: '3308|3306'
        links:
            - php
        ports:
            - 8181:80
